<?php

$SESSIONPREFIX = "PIGOZNIS_TAXI_";

$SESSIONCREDS = $SESSIONPREFIX."CREDS";

$SESSIONNOTIF = $SESSIONPREFIX."MSG_";
$SESSIONNOTIF_ERR = $SESSIONNOTIF."ERR";
$SESSIONNOTIF_INF = $SESSIONNOTIF."INF";
$SESSIONNOTIF_OK = $SESSIONNOTIF."OK";